name: user_agent_mock
description: A library to mock any common userAgents.
version: 0.1.0
repository: https://github.com/shirne/user_agent_mock

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
